### ISSUE TITLE
Create cutting pattern from solved AMPL

### ISSUE THREAD

**Issue by trancefreak77** [MuamerHr/CuttingAndPacking#1]
Hi,

I just found your implementation and I am really impressed how you did this especially with regards to the AMPL solving part. I used your AMPL model, data and command file and let an online solver solve it. The output is as you stated in your PDF that only 491 stocks are needed compared to the heuristically calculated 508 stocks.

Do you know if there is a chance to create the cutting pattern out of the output of the AMPL solver? I have added the output here.
It would be really gread if you could share your knowledge with me how to generate the cutting pattern out of the solver output below.

Kind Regards,
Christian

Solver Output:
BPMPD 2.11: Optimal solution found, objective 490.0969705
14 iterations, 25 corrections (1.79 per iter.)
x [*] :=
  j1  85.142         j206   9.69978e-10   j313   2.21718e-06
 j10   4.91757e-09   j207   6.41563e-10   j314   6.3217e-09
j100   2.16035e-07   j208   3.81981e-10   j315   1.0401e-09
j101   6.96224e-09   j209   3.92736e-10   j316   4.94057e-10
j102   1.44319e-09    j21   5.99268e-07   j317   2.05685e-07
j103   3.04803e-08   j210   3.96415e-10   j318   2.21203e-09
j104   2.52774e-09   j211   2.0862e-09    j319   9.6769e-10
j105   8.07123e-10   j212   2.49829e-09    j32   1.01812e-08
j106   4.27835e-07   j213   1.30956e-09   j320   6.39883e-10
j107   2.39861e-09   j214   2.1399e-09    j321   4.18182e-10
j108   2.19411e-08   j215   1.17621e-09   j322   5.15149
j109   1.98303e-09   j216   5.36868e-09   j323   2.44601e-08
 j11   1.26353e-09   j217   1.43032e-09   j324   1.85285e-09
j110   3.44944e-07   j218   3.80353e-09   j325   9.0309e-10
j111   4.69643e-09   j219   1.29232e-09   j326   6.05407e-10
j112   1.72203e-09    j22   4.88963e-09   j327   3.62429e-10
j113   8.79957e-10   j220   6.5916e-10    j328   3.70252e-10
j114   6.29588e-10   j221   6.79043e-10   j329   4.08199e-07
j115   4.53132e-10   j222   2.24184e-09    j33   1.01095e-08
j116   4.59396e-10   j223   2.37209e-07   j330   5.10527e-09
j117   5.43668e-09   j224   5.8498e-09    j331   1.59813e-09
j118   6.38138e-09   j225   1.43577e-09   j332   8.47677e-10
j119   2.07513e-08   j226   3.30779e-08   j333   5.76885e-10
 j12   1.07787e-07   j227   2.65977e-09   j334   4.61503e-10
j120   9.66803e-09   j228   8.07257e-10   j335   3.28492e-10
j121   1.90648e-09   j229   5.37632e-07   j336   3.32921e-10
j122   1.00644e-09    j23   1.55915e-09   j337   8.82504e-08
j123   1.40605e-08   j230   2.41966e-09   j338   2.84554e-09
j124   1.43403e-08   j231   2.08779e-08   j339   1.43401e-09
j125   7.96065e-06   j232   1.96388e-09    j34   2.61855e-09
j126   4.23723e-09   j233   2.98617e-07   j340   8.04279e-10
j127   1.87454e-06   j234   4.2223e-09    j341   5.53306e-10
j128   3.34818e-09   j235   1.63647e-09   j342   4.4083e-10
j129   1.06793e-08   j236   8.69306e-10   j343   2.94018e-10
 j13   7.20393e-08   j237   6.27817e-10   j344   2.9987e-10
j130   1.03513e-08   j238   4.51706e-10   j345   3.02396e-10
j131   2.61004e-09   j239   4.57637e-10   j346   2.9544e-07
j132   1.3433e-08     j24   8.48845e-10   j347   1.80721e-08
j133   2.13986e-09   j240   2.20126e-09   j348   2.39326e-09
j134   1.01955e-08   j241   2.38567e-07   j349   1.31579e-09
j135   2.62847e-09   j242   5.96261e-09    j35   1.35471e-06
j136   1.94562e-08   j243   1.44071e-09   j350   7.71051e-10
j137   2.1781e-09    j244   3.36029e-08   j351   5.35034e-10
j138   1.05639e-08   j245   2.64765e-09   j352   4.23919e-10
j139   2.64778e-09   j246   8.08855e-10   j353   3.63723e-10
 j14   5.34178e-09   j247   2.02045e-09   j354   2.72037e-10
j140   1.49381e-08   j248   1.15623e-07   j355   2.75395e-10
j141   2.20942e-09   j249   1.5514e-09     j36   2.61484e-09
j142   3.00098e-07    j25   5.4394e-10     j37   3.0902
j143   6.4269e-09    j250   1.03302e-08    j38   2.64599e-09
j144   1.4875e-09    j251   1.37422e-09    j39   1.61953e-06
j145   2.90092e-09   j252   4.01231e-07     j4   9.1239e-08
j146   5.49811e-07   j253   2.85351e-09    j40   2.64637e-09
j147   2.39835e-09   j254   4.8014e-08     j41   2.63641e-07
j148   2.86492e-08   j255   2.21393e-09    j42   5.85879e-09
j149   2.02719e-09   j256   2.93872e-07    j43   1.48696e-09
 j15   1.26881e-09   j257   7.73191e-09    j44   7.67835e-07
j150   5.94005e-07   j258   2.09502e-09    j45   4.16534e-09
j151   5.01484e-09   j259   1.0395e-09     j46   6.85039e-08
j152   1.39238e-07    j26   0              j47   3.22029e-09
j153   3.72022e-09   j260   6.59434e-10    j48   1.21338e-09
j154   1.55066e-09   j261   5.04832e-10    j49   7.81156e-10
j155   8.35514e-10   j262   3.35558e-10     j5   1.83714e-08
j156   5.98244e-10   j263   3.42363e-10    j50   5.63078e-10
j157   3.94559e-10   j264   3.45066e-10    j51   5.68384e-10
j158   4.0143e-10    j265   0.665412       j52   5.46857e-08
j159   7.8322e-06    j266   2.19231e-09    j53   3.50349e-08
 j16   1.79226e-09   j267   5.41301e-08    j54   4.28517e-08
j160   3.07781e-09   j268   2.57134e-09    j55 100
j161  17.5065        j269   1.3325e-09     j56   8.43515e-08
j162  15.2708         j27   3.60799e-08    j57   3.97293e-08
j163   2.55054e-09   j270   2.25881e-07    j58   3.79082e-08
j164   1.54978e-06   j271   5.72372e-09    j59   1.78047e-09
j165   2.64205e-09   j272   1.44632e-09     j6  29.7161
j166  14.1289        j273   2.99794e-07    j60   2.29303e-07
j167   2.57144e-09   j274   4.09999e-09    j61   1.1603e-09
j168   1.70196e-06   j275   1.32054e-09    j62   3.59321e-08
j169   2.67773e-09   j276   6.6217e-10     j63   1.83752e-09
 j17   4.23378e-07   j277   6.83018e-10    j64   2.93265e-07
j170   2.50403e-07   j278   3.44527e-08    j65   1.15363e-09
j171   6.0374e-09    j279   2.68243e-09    j66   0.909067
j172   1.49298e-09    j28 119.091          j67   2.80658e-08
j173   9.44083e-07   j280   8.10258e-10    j68   1.10612e-09
j174   3.91733e-09   j281   6.84254e-07    j69   3.11259e-09
j175   1.33723e-09   j282   2.57153e-09     j7   2.61627e-09
j176   6.79313e-10   j283   2.33301e-08    j70   7.99388e-10
j177   6.97296e-10   j284   2.07813e-09    j71   4.67473e-07
j178   2.58853e-09   j285   3.42105e-07    j72   2.48936e-09
j179   2.61548e-09   j286   4.79091e-09    j73   2.33799e-08
 j18   1.939e-09     j287   1.73502e-09    j74   2.14052e-09
j180   6.96931e-08   j288   8.82306e-10    j75   9.48295e-10
j181   4.70578e-09   j289   6.29439e-10    j76   5.19563e-10
j182   1.25863e-09    j29  27.8189         j77   5.38483e-10
j183   2.85958e-07   j290   4.52635e-10    j78   5.44121e-10
j184   7.03449e-08   j291   4.58848e-10    j79   0.574546
j185   6.3202e-09    j292   2.02535e-09     j8   2.641e-09
j186   1.26391e-09   j293   1.24379e-07    j80   2.23003e-09
j187   2.44071e-07   j294   1.57058e-09    j81   5.77079e-08
j188   6.99389e-08   j295   1.12816e-08    j82   2.52777e-09
j189   4.84136e-09   j296   1.39521e-09    j83   1.34396e-09
 j19   1.06043e-08   j297   4.47844e-07    j84   1.03701e-08
j190   1.269e-09     j298   3.05499e-09    j85  70.2356
j191   1.82132e-09   j299   5.46229e-08    j86   1.64629e-07
j192   5.85086e-07     j3   7.79422e-08    j87   1.01439e-07
j193   1.94586e-09    j30   1.37704e-08    j88   6.43636e-08
j194   2.82654e-05   j300   2.38345e-09    j89   4.69208e-09
j195   6.7252e-08    j301   3.34559e-07     j9   6.76598e-08
j196   9.46501e-10   j302   8.78388e-09    j90   1.26912e-09
j197   5.07738e-09   j303   2.04406e-09    j91   2.19829e-09
j198   1.2125e-09    j304   1.08219e-09    j92   2.21429e-09
j199   4.95105e-07   j305   6.67338e-10    j93   1.9511e-07
  j2   1.16386e-07   j306   5.058e-10      j94   5.76647e-09
 j20   1.71932e-09   j307   3.35764e-10    j95   1.43804e-09
j200   2.95643e-09   j308   3.42674e-10    j96   0.796432
j201   3.68267e-08   j309   3.45414e-10    j97   2.2119e-09
j202   2.35183e-09    j31   7.87064e-07    j98   5.1766e-08
j203   4.51811e-07   j310   1.04822e-06    j99   2.5419e-09
j204   5.41303e-09   j311   3.29299e-08
j205   2.02224e-09   j312   8.9262e-10
;

sum{j in col} x[j] = 490.097
== 1 ==========================

**Comment by MuamerHr** [comment]
Hello Christian,

I'm excited to hear that my code drew your attention and that it worked.
Thank you!

I understand your issue but it isn't really a issue.
You already have the cutting patterns :-D.

The AMPL-DAT file "cuttingPattern.dat" is generated with the 
"CuttingPattern.cs" class and allready contains all feasible
dominant cutting patterns.

####################################################################################################
If you take the example from the CuttingStockTest Main():

1)	int[] lengths = new int[10] { 6000, 5500, 5200, 4800, 4400, 3500, 2500, 2400, 1700, 1150 };
	int[] amounts = new int[10] { 200, 150, 220, 100, 100, 264, 80, 156, 50, 150 };
	int maxLength = 12000;
	
Now lets look at the "cuttingPattern.dat":

set lengths :=	l1	l2	l3	l4	l5	l6	l7	l8	l9	l10;
set col :=	j1	j2	j3	j4	j5	j6	j7	j8	j9	j10	j11	...;
// lengths:	6000	5500	5200	4800	4400	3500	2500	2400	1700	1150

param cutScheme :		l1	l2	l3	l4	l5	l6	l7	l8	l9	l10:=
					j1	2	0	0	0	0	0	0	0	0	0
					j2	1	1	0	0	0	0	0	0	0	0
					...
					;
					
Every row is a feasible and dominant cutting pattern. (Explanation of the terms feasible and dominant
down below). Each entry "i" in a row corresponds to the length "l[i]".

Take row 1 as example:

j1 	2	0	0	0	0	0	0	0	0	0

This cutting pattern literally stands for: 
"Cut length l1=6000 2 times from one stock and nothing else (zeroes)." 
or from another view
"Length l1=6000 fits 2 times into a stock of length 12000".

Row 2 says:

j2 	1	1	0	0	0	0	0	0	0	0

"Cut lengths l1=6000 and l2=5500 from a stock of 12000."
which also implies that there is waste of length 12000-(6000+5500)=500.

-Feasible means that the sum of the lengths to cut does not exceed the max. length of the stock.
-Dominant means that there are no cutting patterns where the waste is greater than the smallest length.
e.g.: MaxLength=10, l1=5, l2=2. Than the cutting pattern 

jk	0	1

is ignored (and not included) because there is waste of length 10-2=8.
This cutting pattern is "dominated" by the cutting pattern

j*	0	5


####################################################################################################

Now take the variables x from the AMPL- Model.
Variable x[j1] corresponds to cutting pattern j1 and so on.

Now look at the results of the solver :

x [*] :=
j1 85.142 j206 9.69978e-10 j313 2.21718e-06
j10 4.91757e-09 j207 6.41563e-10 j314 6.3217e-09
...
;

x[j1]=85.142 stands for: "Take cutting pattern 

j1 	2	0	0	0	0	0	0	0	0	0

and cut it 85.142 times, and so on.

(By the way the result is a bit bothering because x is a integer variable and the 
result should also be an integer. Maybe the solver supressed the option

"var x {j in col} integer >= 0;	#variable to indicate how often cutting pattern cutScheme[*,j] is used"?)

and so on. 

Summary:
1) The CuttingPattern.dat contains all feasible cutting patterns for a given input.
To a given input it will be generated by the C# code. (CuttingStock)
2) The AMPL-Model minimizes the usage of the possible cutting patterns while trying to
satisfy the needed amounts of the lengths.(Maybe not all pattern are necessary).
3) The resulting x[j]'s indicate how often to use pattern j for the optimal solution.

I think this (not very short, sorry ^^) explanation should solve your issue.

With kind regards
Muamer

**Comment by trancefreak77** [comment]
Hi Muamer,

Thanks very much for your detailed explanation. It looks like not all solvers interpret the AMPL commands or model the same. I got it working with correct calculated numbers for each pattern only with the CPLEX solver. The solvers I tried from this page https://ampl.com/try-ampl/start/ do all return weird pattern numbers. Only the CPLEX solver on the NEOS page does everything correct.

Do you have an idea why other solvers do not interpret the standardized AMPL syntax correctly?

Kind Regards,
Christian

**Comment by MuamerHr** [comment]
Hello Christian,

I visited the ampl homepage and had a look on the solver list.
Maybe the solvers are not able to solve integer programming problems and
respectively mixed integer programming problems and that is the reason
why you get results which are not integral.
The cutting stock problem belongs to the class of the mentioned problem.

I have attached a result of the SCIP solver from the NEOS-Server.
[SCIP_Result.txt](https://github.com/MuamerHr/CuttingAndPacking/files/5287096/SCIP_Result.txt)

Not every solver is suited for every problem. CPLEX, SCIP, Gurobi or Couenne are 
able to solve such problems like the cutting stock problem (and many others).

I think the best way to get a first overview, which solver can solve
which type of problem, is to visit https://neos-server.org/neos/solvers/index.html
and to search a solver by the problem type.

I have also attached the AMPL guide. The chapter "Relaxing Integrality"
on page 215 (229) shows how to suppress or to force integer results and more
(if the solver is capable to do so ^^).
[AMPLbook.pdf](https://github.com/MuamerHr/CuttingAndPacking/files/5287095/AMPLbook.pdf)

Just try another solver...I guess ^^.

With kind regards
Muamer
